### ISSUE TITLE
Problems with the DigitalOcean droplet

### ISSUE THREAD

**Issue by zird0t** [Piero24/TelegramBot-AmazonOffers#6]
Hi,

I'm having some trouble starting the bot on [the DigitalOcean droplet](https://www.digitalocean.com/products/droplets) on ubuntu 20.04.

I cloned the git, checked that the Amazon keys, bot keys and channel ID are correct.
Ran sudo docker build -t amazon-bot-offers .
Ran sudo docker run -p 8000:8000 amazon-bot-offers

In the photo you can see the error generated:

<img width="1496" alt="telegram-bot-error" src="https://github.com/Piero24/TelegramBot-AmazonOffers/assets/33221393/1d0080b2-8a23-4277-b777-8425a9125b0a">

Thank you!

**Comment by Piero24** [comment]
Hi @zird0t The error should be very simple. I think you forgot to rename the files.

As you can see [here](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/5768c6ce931be30d0222672e9e7e47ac98a05081/.github/api_Keys_Setup.md) and [here](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/5768c6ce931be30d0222672e9e7e47ac98a05081/.github/settings.md) In the first few lines you need to rename the files from `api_keys_template.py` into `api_keys.py` and `settings_template.py` into `settings.py`.

**Comment by zird0t** [comment]
Hi Piero, thanks for the reply.

I'm sorry, I should have read more carefully. I think everything is ok. Now, when I browse IPADDRESS:8000 I see the web page.

Can I do a manual test to see if everything is working correctly? Or should I just wait for the bot to upload an offer to the channel?

**Comment by Piero24** [comment]
No problem @zird0t, glad it’s working now.
However, currently, there is no testing system in place, but it should work. In case of issues, you should check the log files in the log folder. This will help identify any errors if it doesn’t work.

At most, you can do some tests by running the code normally without Docker, temporarily removing the if statement that checks for dates, times, and holidays in the `bot_starer.py`.
